// An object with the Android permissions and its Web API equivalent (sort of)
// Got the initial data visiting http://developer.android.com/reference/android/Manifest.permission.html
// running this in the console: obj = {}; Array.prototype.slice.call(document.body.querySelectorAll('#constants tr td:nth-child(2) a')).forEach(function(a) { obj[a.innerHTML] = ''; }); console.log(JSON.stringify(obj, null, 4))
// and copying the output here
// then editing to find the corresponding API name from here https://developer.mozilla.org/en-US/docs/WebAPI

module.exports = {
    "ACCESS_CHECKIN_PROPERTIES": "",
    "ACCESS_COARSE_LOCATION": "Geolocation",
    "ACCESS_FINE_LOCATION": "Geolocation",
    "ACCESS_LOCATION_EXTRA_COMMANDS": "",
    "ACCESS_MOCK_LOCATION": "",
    "ACCESS_NETWORK_STATE": "WiFi Information",
    "ACCESS_SURFACE_FLINGER": "",
    "ACCESS_WIFI_STATE": "WiFi Information",
    "ACCOUNT_MANAGER": "",
    "ADD_VOICEMAIL": "Voicemail",
    "AUTHENTICATE_ACCOUNTS": "",
    "BATTERY_STATS": "Battery",
    "BIND_ACCESSIBILITY_SERVICE": "",
    "BIND_APPWIDGET": "",
    "BIND_DEVICE_ADMIN": "",
    "BIND_INPUT_METHOD": "",
    "BIND_NFC_SERVICE": "",
    "BIND_NOTIFICATION_LISTENER_SERVICE": "",
    "BIND_PRINT_SERVICE": "",
    "BIND_REMOTEVIEWS": "",
    "BIND_TEXT_SERVICE": "",
    "BIND_VPN_SERVICE": "",
    "BIND_WALLPAPER": "",
    "BLUETOOTH": "Bluetooth",
    "BLUETOOTH_ADMIN": "Bluetooth",
    "BLUETOOTH_PRIVILEGED": "Bluetooth",
    "BRICK": "",
    "BROADCAST_PACKAGE_REMOVED": "",
    "BROADCAST_SMS": "",
    "BROADCAST_STICKY": "",
    "BROADCAST_WAP_PUSH": "",
    "CALL_PHONE": "WebTelephony",
    "CALL_PRIVILEGED": "WebTelephony",
    "CAMERA": "Camera",
    "CAPTURE_AUDIO_OUTPUT": "GetUserMedia",
    "CAPTURE_SECURE_VIDEO_OUTPUT": "GetUserMedia",
    "CAPTURE_VIDEO_OUTPUT": "GetUserMedia",
    "CHANGE_COMPONENT_ENABLED_STATE": "",
    "CHANGE_CONFIGURATION": "Settings",
    "CHANGE_NETWORK_STATE": "Settings",
    "CHANGE_WIFI_MULTICAST_STATE": "Settings",
    "CHANGE_WIFI_STATE": "Settings",
    "CLEAR_APP_CACHE": "",
    "CLEAR_APP_USER_DATA": "",
    "CONTROL_LOCATION_UPDATES": "",
    "DELETE_CACHE_FILES": "",
    "DELETE_PACKAGES": "",
    "DEVICE_POWER": "",
    "DIAGNOSTIC": "",
    "DISABLE_KEYGUARD": "",
    "DUMP": "",
    "EXPAND_STATUS_BAR": "",
    "FACTORY_TEST": "",
    "FLASHLIGHT": "Camera",
    "FORCE_BACK": "",
    "GET_ACCOUNTS": "",
    "GET_PACKAGE_SIZE": "",
    "GET_TASKS": "",
    "GET_TOP_ACTIVITY_INFO": "",
    "GLOBAL_SEARCH": "",
    "HARDWARE_TEST": "",
    "INJECT_EVENTS": "",
    "INSTALL_LOCATION_PROVIDER": "",
    "INSTALL_PACKAGES": "Open Web Apps",
    "INSTALL_SHORTCUT": "",
    "INTERNAL_SYSTEM_WINDOW": "",
    "INTERNET": "TCP Socket",
    "KILL_BACKGROUND_PROCESSES": "",
    "LOCATION_HARDWARE": "",
    "MANAGE_ACCOUNTS": "",
    "MANAGE_APP_TOKENS": "",
    "MANAGE_DOCUMENTS": "",
    "MASTER_CLEAR": "",
    "MEDIA_CONTENT_CONTROL": "Audio Policy",
    "MODIFY_AUDIO_SETTINGS": "Audio Policy",
    "MODIFY_PHONE_STATE": "",
    "MOUNT_FORMAT_FILESYSTEMS": "Device Storage",
    "MOUNT_UNMOUNT_FILESYSTEMS": "Device Storage",
    "NFC": "WebNFC",
    "PERSISTENT_ACTIVITY": "",
    "PROCESS_OUTGOING_CALLS": "WebTelephony",
    "READ_CALENDAR": "Calendar API",
    "READ_CALL_LOG": "",
    "READ_CONTACTS": "Contacts API",
    "READ_EXTERNAL_STORAGE": "Device Storage",
    "READ_FRAME_BUFFER": "",
    "READ_HISTORY_BOOKMARKS": "",
    "READ_INPUT_STATE": "",
    "READ_LOGS": "",
    "READ_PHONE_STATE": "",
    "READ_PROFILE": "",
    "READ_SMS": "WebSMS",
    "READ_SOCIAL_STREAM": "",
    "READ_SYNC_SETTINGS": "",
    "READ_SYNC_STATS": "",
    "READ_USER_DICTIONARY": "",
    "REBOOT": "",
    "RECEIVE_BOOT_COMPLETED": "",
    "RECEIVE_MMS": "WebMMS",
    "RECEIVE_SMS": "WebSMS",
    "RECEIVE_WAP_PUSH": "",
    "RECORD_AUDIO": "GetUserMedia",
    "REORDER_TASKS": "",
    "RESTART_PACKAGES": "",
    "SEND_RESPOND_VIA_MESSAGE": "",
    "SEND_SMS": "WebSMS",
    "SET_ACTIVITY_WATCHER": "",
    "SET_ALARM": "Alarm",
    "SET_ALWAYS_FINISH": "",
    "SET_ANIMATION_SCALE": "",
    "SET_DEBUG_APP": "",
    "SET_ORIENTATION": "Screen Orientation",
    "SET_POINTER_SPEED": "",
    "SET_PREFERRED_APPLICATIONS": "",
    "SET_PROCESS_LIMIT": "",
    "SET_TIME": "",
    "SET_TIME_ZONE": "",
    "SET_WALLPAPER": "",
    "SET_WALLPAPER_HINTS": "",
    "SIGNAL_PERSISTENT_PROCESSES": "",
    "STATUS_BAR": "",
    "SUBSCRIBED_FEEDS_READ": "",
    "SUBSCRIBED_FEEDS_WRITE": "",
    "SYSTEM_ALERT_WINDOW": "",
    "TRANSMIT_IR": "",
    "UNINSTALL_SHORTCUT": "",
    "UPDATE_DEVICE_STATS": "",
    "USE_CREDENTIALS": "",
    "USE_SIP": "",
    "VIBRATE": "Vibration",
    "WAKE_LOCK": "Power Management",
    "WRITE_APN_SETTINGS": "Settings",
    "WRITE_CALENDAR": "Calendar",
    "WRITE_CALL_LOG": "",
    "WRITE_CONTACTS": "Contacts",
    "WRITE_EXTERNAL_STORAGE": "Device Storage",
    "WRITE_GSERVICES": "",
    "WRITE_HISTORY_BOOKMARKS": "",
    "WRITE_PROFILE": "",
    "WRITE_SECURE_SETTINGS": "",
    "WRITE_SETTINGS": "Settings",
    "WRITE_SMS": "WebSMS",
    "WRITE_SOCIAL_STREAM": "",
    "WRITE_SYNC_SETTINGS": "",
    "WRITE_USER_DICTIONARY": ""
};
